version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: chioma_db
    restart: always
    environment:
      POSTGRES_USER: postgres_cax
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chioma_db
    ports:
      - "5433:5432"
    volumes:
      - chioma_postgres_data:/var/lib/postgresql/data

volumes:
  chioma_postgres_data:
